// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAuQzu2kua9ctbSqC7vOlnb4w9YXPfMxC0',
    appId: '1:651919912678:android:e0eb3728f575f0b8eb1527',
    messagingSenderId: '651919912678',
    projectId: 'quopon-8b833',
    storageBucket: 'quopon-8b833.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD0wGMggDxlXXuRvx7rfVMViCeeQjh_6NQ',
    appId: '1:651919912678:ios:b594543881ef59ffeb1527',
    messagingSenderId: '651919912678',
    projectId: 'quopon-8b833',
    storageBucket: 'quopon-8b833.firebasestorage.app',
    iosBundleId: 'com.quopon.quopon.quopon',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBOF4vljrrs_Q9GxIvqbx9JzipiiZm-AoI',
    appId: '1:651919912678:web:8b4687af505d84b1eb1527',
    messagingSenderId: '651919912678',
    projectId: 'quopon-8b833',
    authDomain: 'quopon-8b833.firebaseapp.com',
    storageBucket: 'quopon-8b833.firebasestorage.app',
    measurementId: 'G-0WBXQLR7X8',
  );

}